[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino

monitor_speed = 115200

lib_deps =
    m5stack/M5Unified
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit SGP30 Sensor
    m5stack/M5Unit-ENV
